schemas/groups/navigation.json
added distanceActual for current distance to the next waypoint.
Has to be clarified if Meters or Nautical Miles
=> Add waypoint.distanceActual, correct units for log & logTrip

schemas/groups/performance.json
=> Define specification for Performance data

mappings/README-n2k.txt, mappings/n2kMappings.json
@rob42 - if this is what you intended with #60 go ahead and close #60 and merge this.
=> Added n2kMappings

schemas/groups/electrical_ac.json, schemas/vessel.json
New addition to the spec: Electrical AC parameters. This covers PGNs 65001 - 65030.
=> Electrical, AC

schemas/vessel.json
Standardize the formatting of description values.
=> Format vessel.json

schemas/groups/design.json, schemas/groups/electrical_ac.json, schemas/groups/electrical_dc.json, schemas/groups/navigation.json
Lowercase with spaces for multiple words
Fixes #73
=> Format all enums to the same style

schemas/vessel.json
=> Added an UUID property to vessel.json

schemas/groups/navigation.json
Format the descriptions in the navigation group.
=> Format the navigation group

schemas/groups/resources.json
Format the descriptions in the `resources` group
=> Format the resources group

schemas/groups/electrical_dc.json
This introduces a breaking change as some of the properties were renamed
to correct for typos.
=> Format the electrical_dc group

schemas/groups/design.json
Format the descriptions in the design group
=> Format the design group

schemas/definitions.json, test/validation.js
PGN is always a number so make it one in the schema
=> Change pgn type to number

schemas/groups/environment.json
Be explicit about how 'true' wind angle has been calculated.
=> Split angleTrue

schemas/groups/environment.json, schemas/groups/navigation.json
These got left behind somehow. Need to be removed
=> Relocate current from navigation to environment

schemas/definitions.json, schemas/groups/design.json, schemas/groups/electrical_dc.json, schemas/groups/environment.json, schemas/groups/navigation.json, schemas/groups/performance.json, schemas/groups/propulsion.json, schemas/groups/resources.json, schemas/groups/steering.json
=> Implement my own suggestion in issue #112

index.js, keyswithmetadata.json, schemas/definitions.json, schemas/groups/design.json, schemas/groups/electrical_ac.json, schemas/groups/electrical_dc.json, schemas/groups/environment.json, schemas/groups/navigation.json, schemas/groups/performance.json, schemas/groups/propulsion.json, schemas/groups/resources.json, schemas/groups/sails.json, schemas/groups/sensors.json, schemas/groups/steering.json, schemas/groups/tanks.json, scripts/extractKeysAndMeta
This should be everything.
The list of used units at the moment is:
```"A"
"C"
"Hz"
"J"
"K"
"Pa"
"V"
"W"
"deg"
"kg"
"m"
"m/s"
"m2"
"m3"
"m3/s"
"rad"
"rad/s"
"ratio"
"s"
```
=> Change all units to (derived) SI units (fix issue #30)

schemas/groups/navigation.json
Quality, Integrity and PDOP  added.
=> Additional GNSS field added

schemas/groups/environment.json
Although it was not in my list of PGNs to be supported by iKommunicate V1, I know that some of you have been playing with 9 axis sensors and so perhaps it would be useful to have Heave included in SK. Basically negative measurement value means you are moving up on a wave and positive value means you are going down in to the trough of a wave.
=> Add Heave to environment.json

.gitignore, schemas/groups/navigation.json
We probably should allow for chain counters etc.
=> Added scope to anchor

samples/vessel-time.json, schemas/groups/environment.json, test/vessel-time.js
No test, but sample data in vessel-time.json
=> Added time object and sample to environment.json

samples/vessel-time.json, schemas/groups/environment.json, test/vessel-time.js
This is the same pull request as #126 Adding system time, but that request was aginst v1-beta1, and once merged would not nicely commit just the systime stuff to master without bringing along other v1-beta1 changes.
Hence a new branch, artfully cherry-picked, just for master :-)
=> Master add systime

schemas/vessel.json
=> Added IMO, flag, port, and reg number

samples/vessel-time.json, schemas/groups/environment.json, test/data/env_mode.json, test/env_mode.js
Add source, timestamp, value format and add test
=> Add env.mode - take2 - Add source/timestamp and test

schemas/groups/navigation.json
=> Added lights to navigation 

schemas/vessel.json, test/data/registrations.json, test/registrations.js
Replaces #144 with a registrations tree structure, allowing multiple national, local and other registrations
=> Added registration structure

LICENSE, package.json
ping @SignalK/core, I'd like somebody else to sign this off.
=> Use SPDX abbreviation of the license

schemas/groups/electrical_dc.json, test/data/electrical_dc.json, test/electrical_dc.js
DC schema had a bunch of reference & structural errors and could not handle more than one battery.
This pull request fixes batteries, but inverter part still needs work.
Test includes a sample document with multiple batteries.
=> Rework electrical dc: batteries

samples/signalk-depth-meta-attr.json, schemas/definitions.json, schemas/groups/alarms.json, schemas/vessel.json, test/alarms.js, test/data/alarms-deep.json, test/data/alarms-invalid1.json, test/data/alarms-invalid2.json, test/data/alarms.json
Add alert and emergency types, and improve descriptions
=> Improve alarms - add alert and emergency

schemas/groups/performance.json
Since we have variables for polar speed, it might be prudent to make reference to the polar diagram rather than "current polar"
=> Improve descriptions

schemas/groups/propulsion.json
Ref. issue #189
Originally by @joabakk #192. I pushed propeller properties down one hierarchy level, fiddled with the descriptions and fixed indentation.
=> Unit cleanup and added prop slip dependancies

schemas/groups/tanks.json, schemas/vessel.json, test/data/tanks.json, test/tanks.js
- use branches
- rename level to currentVolume
=> Refactor tanks

schemas/groups/electrical.json
State of Health is the overall status of the battery based on the life of the battery - 0-100%
=> Added State of Health to Batteries

schemas/groups/environment.json, test/data/temperatures.json
Typo and matches better with freezer, heater and well
=> Renamed refridgeration to refrigerator

schemas/groups/environment.json, test/data/temperatures.json
- remove air hierarchy level
- drop well hierarchy level
- move baitWell and liveWell under water
=> Reorganise temperatures a bit

keyswithmetadata.json, scripts/extractKeysAndMeta.js
@sailoog is this what you're after in #227 ?
=> Include enums in keyswithmetadata.json

schemas/definitions.json, schemas/delta.json, test/data/course.json, test/sources.js
This is issue is for discussing source handling for all kinds of sources, NMEA and non-NMEA alike.
=> Source handling for NMEA and non-NMEA sources

gitbook-docs/README.md
Wrap to 120 characters
Fixes some spelling, clarifies language and expands a few topics
This should be fairly straightforward, I'd just like to get a couple of sign-offs before merging.
=> Clarify gitbook-docs/README.md

schemas/groups/sources.json, test/data/sources.json
Removed redundent enteries, reloated N2K specific informaiton to N2K
section, scrubbed type of productId from string to number.
Referance RFC 0001
=> Cleanup of sources schema

i18n/en.json, schemas/groups/steering.json, test/data/steering.json, test/steering.js
Created a separate branch on my side, ref#251
Changes to be committed:
modified:   i18n/en.json
modified:   schemas/groups/steering.json
new file:   test/data/steering.json
new file:   test/steering.js
=> Reorganized steering group, added test

gitbook-docs/SUMMARY.md, gitbook-docs/changelog.md
Add Changelog as part of the documentation.
=> Add Changelog

i18n/en.json, schemas/groups/steering.json, test/data/steering.json
As discussed with @tkurki and @sbender9, this tweak allows the co-existence of wind and heading angles.
=> Steering group in line with autopilot communication

.travis.yml, src/fullsignalk.js, test/sources.js
Generate arbitrary hierarchy under /sources using $source as period
delimited path.
See https://github.com/SignalK/specification/pull/238 and  https://github.com/SignalK/signalk-server-node/issues/101
=> Add support for dollarpath in FullSignalK

gitbook-docs/data_model_multiple_values.md, gitbook-docs/subscription_protocol.md
The doc is outdated and doesn't match the schema nor the specified logic related to having multiple values in the full model, linked to sources.
TODO:
=> Update multiple values documentation

schemas/definitions.json, schemas/groups/environment.json, test/data/lux-i2c.json, test/data/lux.json, test/env_lux.js
=> Added illuminance

gitbook-docs/data_model_metadata.md
=> Add note that meta.units MUST be returned for valid keys

gitbook-docs/data_model.md
See #242
Not critical, but best to say it to remove doubt.
=> Add note on data accuracy

gitbook-docs/data_model_multiple_values.md, test/data/multiple-values.json, test/sources.js
The multiple sources/values documentation is really out of data and does not reflect current thinking and implementation. This PR adds a test case for multiple values in the full tree and....
TODO
=> Rewrite multiple sources/values documentation

index.js, package.json, schemas/aircraft.json, schemas/aton.json, schemas/def_loader.json, schemas/def_loader_pre.json, schemas/definitions.json, schemas/delta.json, schemas/discovery.json, schemas/groups/communication.json, schemas/groups/design.json, schemas/groups/electrical.json, schemas/groups/environment.json, schemas/groups/navigation.json, schemas/groups/notifications.json, schemas/groups/performance.json, schemas/groups/propulsion.json, schemas/groups/resources.json, schemas/groups/sails.json, schemas/groups/sensors.json, schemas/groups/sources.json, schemas/groups/steering.json, schemas/groups/tanks.json, schemas/sar.json, schemas/signalk.json, schemas/vessel.json
This changes all current files with a schema, and sets up the npm script to work correctly for next `npm run schema:version`
=> Change from schemas/version to version/schemas

schemas/groups/propulsion.json, test/data/propulsion.json
Here's a new parameter to propulsion schema.
Is there anything else I need to change for this?
=> Add intakeManifoldTemperature to propulsion schema

schemas/groups/environment.json
This can be useful in comparing sail performance in different conditions
=> Add outside air density

scripts/processSchemaFiles.js, src/keyswithmetadata.json
=> feature: include enums in keyswithmetadata

schemas/groups/navigation.json, test/cpa_tcpa.js, test/data/ais-cpa-tcpa.json
Placeholders to calculate for collision avoidance
=> Add CPA and TCPA

scripts/processSchemaFiles.js
=> feature: specify WGS84 for coordinates

gitbook-docs/connection.md
This is a fantastic project by the way. Thanks :D
=> Fix typo in connection.md

package.json, schemas/signalk.json
=> Root relative self

schemas/definitions.json
Added:
- Mass Flow Rate
- Torque
- Viscosity
Also made some other corrections to units particularly quantityDisplay was incorrect.
These are additions and effectively corrections to documentation so are backward compatible.
=> Additional units with corrections

gitbook-docs/sources.md
Minor change to make pointer example schema compliant
=> Modified pointer example to be schema compliant

schemas/groups/navigation.json
Implements Issue #401 - enhances the description of Magnetic Variation.
I have verified and concur with the description suggested by @sumps except I have removed the reference to 'vessel' as Magnetic Variation applies equally to aircraft etc.
=> Modify description of Magnetic Variation

schemas/groups/sources.json
These props got lifted by mistake in ed7b75c. This corrects that.
=> Put descriptive source properties where they belong

gitbook-docs/data_model.md, gitbook-docs/sources.md
=> Add Documentation for Sources

schemas/groups/environment.json, test/data/vessel-invalid/environment-with_inside_heatIndex.json, test/data/vessel-valid/environment-with_inside_heatIndexTemperature.json
fixes #446.
Adds heatIndexTemperature to inside zones to be consistent with outside.
Also added a valid and invalid test.
=> feature: add heatIndexTemperature to environment inside zones

schemas/groups/environment.json, test/data/vessel-invalid/environment-inside humidity rather than relativeHumidity.json, test/data/vessel-invalid/environment-inside invalid property.json, test/data/vessel-valid/environment-sample.json
Fixes issue #444 
Removes hard coded inside zones eg. mainCabin, engineRoom and replaces with user definable to allow eg. portEngineRoom, aftCabin, etc.
All existing tests pass unchanged. Added 1 valid and 2 invalid tests.
=> Fix Environment Schema and add tests

schemas/groups/sails.json, test/data/vessel-valid/sails-sample.json
=> Add reef and furl state to sails

gitbook-docs/data_model_metadata.md, samples/full/docs-data_model_metadata.json, samples/full/signalk-depth-meta-attr.json, schemas/definitions.json, schemas/groups/sails.json, test/data/vessel-valid/sails-sample.json
Remove gauge type from meta.
closes #409
=> chore: remove deprecated gaugeType

gitbook-docs/data_model_metadata.md, samples/full/docs-data_model_metadata.json, samples/full/signalk-depth-meta-attr.json, schemas/definitions.json
=> chore: mark gaugeType as deprecated, update documentation and samples

gitbook-docs/connection.md
Fix broken link in connection.md
=> chore: fix broken link in documentation

gitbook-docs/data_model.md, gitbook-docs/subscription_protocol.md, samples/delta/docs-data_model_meta_deltas.json
Add more detail to documentation of meta deltas
=> docs: modify re meta deltas

gitbook-docs/rest_api.md
Add a mention of optional support for http/2.
=> doc: add MAY re: http/2

README.md
=> docs: fix readme validation error

schemas/groups/sails.json, test/data/vessel-invalid/sails-sample.json
=> Fix: reducedState as object

schemas/groups/navigation.json
=> Added headingRaw, and magneticDeviation, adjust descriptions to be clearer

gitbook-docs/apps_api.md
Documenting the `signalk/v1/apps` API
=> Add Apps API page

src/fullsignalk.js
Currently any meta data in defaults will overwrite meta in from the schema
=> fix: merge meta from spec with meta from defaults

package.json, schemas/aircraft.json, schemas/aton.json, schemas/definitions.json, schemas/delta.json, schemas/discovery.json, schemas/groups/communication.json, schemas/groups/design.json, schemas/groups/electrical.json, schemas/groups/environment.json, schemas/groups/navigation.json, schemas/groups/notifications.json, schemas/groups/performance.json, schemas/groups/propulsion.json, schemas/groups/resources.json, schemas/groups/sails.json, schemas/groups/sensors.json, schemas/groups/sources.json, schemas/groups/steering.json, schemas/groups/tanks.json, schemas/hello.json, schemas/messages/auth.json, schemas/messages/get.json, schemas/messages/put.json, schemas/messages/subscribe.json, schemas/messages/unsubscribe.json, schemas/sar.json, schemas/signalk.json, schemas/vessel.json, src/index.js
The script that was supposed to update the version in the schema files was buggy and only some of the references were updated, resulting in all schema tests failing.
=> fix: schema versioning in the schema files

schemas/groups/environment.json
Add fixed versions and deprecate the erroneous ones.
Supercedes #609.
=> fix: relativeHumidity, dewPointTemperature

schemas/groups/steering.json, test/data/vessel-valid/steering-sample.json
=> feature: add autopilot target windAngleTrue

latest/index.html
Also, testing the direct edit functionality in GitHub - sorry if this PR is wonky!
=> Fix the versioned links in latest/index.html

v2-food-for-thought.md
I am adding this PR and the document thereof to serve as a living document for stuff that we could or should implemement in the next "big" Signal K version.
Not sure how things will work out, but the idea is to discuss in the PR and then edit the doc to contain a somewhat coherent view of things.
Let's see how this turns out - please, discuss here if you have something on your mind or amend this PR by issuing PRs to it.
=> [WIP] SKv2 Food for Thought

schemas/groups/electrical.json
Not sure if there's a better way to specify this? Ideally we'd customize the description of battery current, but I can't see a way to do that.
=> Clarify that positive current charges battery objects
