- index.js
so that Browserify can follow the dependency ch.ain and validation works in browser/Browserify environment
> Change subschema loading 

- index.js
- schemas/delta.json
- test/validation.js
The current delta schema does not explicitly say what a 'value' should be and by itself does not work if we want to validate against extra properties. 
This change specifies value as string/number/object and explicitly allows additionalProperties.
Please notice that I stupidly I created this branch off the one for #62
> More lenient delta schema

- i18n/en.json
- i18n/index.js
- index.js
SignalK data model is mostly self-documenting, but paths from the model are not really meant for human consumption in a UI.
A UI needs nice, potentionally localizable names. These should be universally available, eg. usable in any SignalK UI and since they need to be in sync with the spec the natural home for them is the specification repository.
This PR is not meant to be merged yet, but an invitation to anybody interested to participate. Please help fill in all the missing data either by sending pull requests, in email or by adding ready to copypaste comments on this thread.
> Labels for SignalK data items

- schemas/definitions.json
- schemas/groups/sails.json
This PR is about separating `sails` from the `design` group, as the sails of a vessel are not a design feature.
> Separate group for sails

- schemas/groups/propulsion.json
Format the descriptions in the `propulsion` group.
This introduces a breaking change in that the engine type enum has a spelling change.
> Format the propulsion group

- bin/validate.js
- index.js
- package.json
- test/treeValidation.js
Previously validation code only considered the "vessel" object and not the whole tree. With these changes it is now possible to assert `validSignalK` which is equal to `validFullSignalK` and alternatively `validSignalKVessel`. Furthermore the module exports `validateFull` and `validateVessel`.
> Improve validation

- .editorconfig
- package.json
- samples/signalk-depth-meta-attr.json
- schemas/def_loader.json
- schemas/def_loader_pre.json
- schemas/definitions.json
- schemas/delta.json
- schemas/groups/alarms.json
- schemas/groups/communication.json
- schemas/groups/design.json
- schemas/groups/electrical_ac.json
- schemas/groups/electrical_dc.json
- schemas/groups/environment.json
- schemas/groups/navigation.json
- schemas/groups/performance.json
- schemas/groups/propulsion.json
- schemas/groups/resources.json
- schemas/groups/sails.json
- schemas/groups/sensors.json
- schemas/groups/steering.json
- schemas/groups/tanks.json
- schemas/messages/subscribe.json
- schemas/messages/unsubscribe.json
- schemas/signalk.json
- schemas/vessel.json
Major cleanup of all existing schemas:
- Moved "units" from descriptions to a separate key (to improve documentation)
- Cleaned up indentation differences
- Small changes to various descriptions (mostly related to consistency)
- Fixes in various schemas where they didn't comply with JSONSchema standard or contained JSON parsing errors. 
- Includes changes to "tanks" suggested by @MariusVolkhart
> Housekeeping: cleanup of all schemas

- schemas/groups/communication.json
You just have one call sign for the VHF whether it is a DSC or non-DSC model.
> Removed CallsignDsc

- schemas/def_loader.json
- schemas/definitions.json
`floatValue` appears to be equivalent to `numberValue` and I only found one reference to it in the schemas. This changes `def_loader.json` to use `numberValue` and removes the declaration.
> Replace last use of floatValue with numberValue

- schemas/groups/navigation.json
- test/data/datetime.json
- test/datetime.js
This adds a place in the Signal K data model for datetime information from GNSS, usually GPS.
This is essentially the same as #122 with the value & source grouped in one object and added timestamp & source to be in line with all other values.
> Add datetime with source information to the Signal K model

- schemas/groups/environment.json
Allows us to set the vessel to `night` mode and based on `navigation.state` we can dim the instruments, set the nav lights, or warn if those are incorrectly set. In turn `navigation.state` can be largely derived from other vessel parameters like SOG, motor params, time, etc. So this also makes smart automation easier.
> Added environment.mode

- test/datetime.js
- test/env_mode.js
- test/registrations.js
@tkurki pointed out lodash was not needed in the endpoints tests. It does not need seem to be needed here either so I removed them.
> Remove unneeded references to lodash

- .gitignore
- index.js
- schemas/definitions.json
- schemas/discovery.json
- test/data/endpoints.json
- test/endpoints.js
Added a schema for the endpoint discovery document.
Added simple validation test.
Relaxed definition of what will be accepted for a URL to allow for relative locations and arbitrary protocols.
> Add schema and tests for endpoint discovery

- schemas/vessel.json
- test/data/alarms-deep.json
- test/data/alarms-invalid1.json
- test/data/alarms-invalid2.json
- test/data/alarms.json
Ive updated the alarms wiki page, and removed the uuid per alarm as I dont think its needed. The only use case where there could be problems is if we have an alarm at `...alarms.navigation.position{}` and another alarm comes in `alarms{}` which overwrites the navigation object with the new alarm object. 
The java server will throw an exception and not update, but that loses the incoming alarm. So its really an implementation thing to be sure not to loose alarms?
> Remove alarm uuid from path as its not needed.

- schemas/definitions.json
- schemas/external/geojson/README.txt
- schemas/external/geojson/bbox.json
- schemas/external/geojson/crs.json
- schemas/external/geojson/geojson.json
- schemas/external/geojson/geometry.json
- schemas/groups/navigation.json
- schemas/groups/resources.json
- test/data/resource-position.json
- test/resource-position.js
Moved position{} object to definitions, and reworked regions, routes, waypoints and misc position related structures  to suit. This change is the same as #124, but that pull request was done against v1-beta1, and now difficult to merge to master. So this one is the specific changes cherry-picked against master.
> Master waypoints ref

- samples/signalk-depth-meta-attr.json
- schemas/definitions.json
As teppo pointed out the zones in meta is an array of arrays.The zone definitions are better described by objects as they have fixed formats
This converts the zones array of arrays to an array of objects
> Convert zone in meta to an object

- schemas/groups/environment.json
The current spec has odd Alarm objects inside various groups that are inconsistent and not inline with the way Alarms and Alerts will be handled. These need to be removed
> Remove legacy Alarm objects from Environment Tree

- schemas/groups/performance.json
Some instruments and equipment will give an NMEA value as target boat speed. Meaning if you are sailing too close hauled, you have lost speed and need to fall off and vice versa. This is taken from the polar diagram, but does not distinguish between beat or gybe.
> Added agnostic target speed and target angle

- schemas/groups/tanks.json
We need a Level field as at the moment we only have a Current Volume field which is a derived value only available if you know the capacity of the tank - tank senders only send a level value 0-100
> Tank Senders only provide tank level value

- keyswithmetadata.json
- schemas/groups/navigation.json
- test/data/course.json
Create two course subtrees, one for Great Circle calculated values and
the other for Rhumbline calculated ones.
Fixes #219
> Add GC/RL distinction

- schemas/groups/resources.json
Ive been working on my web chartplotter and I can store and retrieve charts nicely, but I cant easily derive the scale of the chart. This means I cant arrange the layer stack on screen and hi-res charts hide under low-res charts, etc
Adding scale fixes this.
> Added chart scale, and some new charts types

- schemas/definitions.json
- schemas/delta.json
- schemas/groups/environment.json
- schemas/groups/navigation.json
- schemas/groups/notifications.json
- schemas/groups/propulsion.json
- schemas/groups/resources.json
- schemas/groups/sources.json
- schemas/groups/steering.json
- schemas/signalk.json
- schemas/vessel.json
- scripts/extractKeysAndMeta.js
Added subscribe, unsubscribe, get, put, list message types
> Added missing message types

- schemas/groups/tanks.json
- test/data/tanks.json
Tank capacity should be a Signal K numberValue (with value/values/timestamp/source info) instead of a regular number, because it can be updated from for example PGN 127505. 
See also https://github.com/SignalK/n2k-signalk/pull/32
> Make tank capacity numberValue

- gitbook-docs/subscription_protocol.md
[summary]: #summary
This RFC proposes replacing the [JsonPath](http://goessner.net/articles/JsonPath/) expression specified in the subscription protocol with simple wildcards.
[motivation]: #motivation
Current subscription protocol specifies that the path expression can be JsonPath expressions.
I believe that JsonPath is needlessly complex here.
Subscriptions can be expressed sufficiently with the use of a simple wildcard, making server implementation considerably easier.
[design]: #detailed-design
See diff in this pull request. 
The specification change is mainly in the documentation. Subscription message schema could be enhanced with a regexp.
We lose the expressiveness of JsonPath.
[alternatives]: #alternatives
We could specify the JsonPath support as optional and wildcard support as …
> RFC0004 :Replace JsonPath with wildcard in subscription paths

- scripts/processSchemaFiles.js
Falls back to `definitions.json` if not found in the same file.
Fixes #259 
The diff in keys.md after fix: https://gist.github.com/joux3/14ad4d2654e00f556f3dd1563c9f9cf8
> Resolve relative references in the same file

- gitbook-docs/subscription_protocol.md
As I am in the middle of implementing subscriptions I am reading the spec and it is pretty unclear in places. The text says `To unsubscribe all` but the example unsubscribe has `vessels.self` context.
This update makes this part a bit more clear and updates the example unsubscribe message to actually unsubscribe all.
> Use wildcard context in example, mention wildcard

- index.js
- package.json
- schemas/groups/electrical.json
- schemas/groups/resources.json
- schemas/groups/sources.json
- test/schemaReferences.js
These changes add a test for missing schema references. The already existing test actually didn't try to resolve the reference key paths, it was only concerned about files. The changeset also includes fixes for missing schema references.
The fixes include some trivial changes and one that is largely in progress. The trivial ones are:
1. accidentally referring to `$source` instead of `sourceRef`
2. lacking `../definitions.json`
The more WIP one is the handling of `lineString` and `polygon` references in `groups/resources.json`. Do you have any input @rob42? Right now I just reference the `external/geojson/geometry.json` using relative links. This however leads to certain issues as the ID of the `geometry.json` schema is `http://json-schema.org/geojson/geometry.json` (which BTW is a 404). …
> Validate missing schema references & fix missing references

- gitbook-docs/connection.md
Clarify mDNS/Bonjour and explain that the process being used is DNS-SD
via mDNS. This should give anyone who needs to implement this on a
platform without a ready-to-hand mDNS client library to get started in
the right direction.
Describe the fields or attributes which MUST, SHOULD and MAY be present
in the TXT record of the service advertisements and update the examples
to match.
Add a link to the section of the documentation which explains the
endpoints API and remove the example endpoint JSON as it is already
described in the other section.
> Expand on the Discovery Section

- schemas/groups/navigation.json
A new generation of electro magnetic transducers that can measure the boat's speed through the water both longitudinal and transverse will provide a view of the boat's "Leeway" that was previously difficult to accurately calculate. Signal K needs to support these new transducers which will output the VBW sentence or PGN 130578.
> Add Transverse Water Speed and Leeway Angle

- schemas/groups/navigation.json
As pointed out by @canboat, whether the waterspeed is measured inside or outside the boundary layer is a feature of the sensor and should not be dictated by the schema. Therefore have removed mention of the boundary layer in the description of Longitudinal Speed.
> Removed refererence to Boundary Layer

- index.js
- package.json
- schemas/definitions.json
- schemas/groups/navigation.json
- test/data/course.json
This PR "itemizes" course properties: each is pushed under `value` property and accompanied with timestamp, source and values structure.
This makes possible to update them individually and retain source and timestamp information. 
More importantly this is in line with using just leaf paths in delta.
The possible backwards compatibility issue with this is that if a source has produced object valued deltas it should now send scalar-valued deltas, with the properties in individual pathvalues.
> Itemize course properties

- .npmrc
- gitbook-docs/data_model.md
- gitbook-docs/start_using.md
- package.json
This change in documentation makes two things explicit:
- `context` is in practice always a vessel path
- `path` is a leaf path
My Signal K related code in lots of places assumes that context is a vessel path to discern  self data from other vessels' data. It would be possible to do just prefix matching, but grouping by vessel is a natural way to handle current Signal K data. One would need to extract the vessel identity anyway in these cases.
Omission of context meaning self context is also well in line with this thinking.
#311 posed the question about should paths be leaf paths. I believe this constraint should be explicit in the documentation. Discerning leaves from the current schema is not always very easy, witness #299, and I think we need to change the schema to make leaves more …
> Specify vessel context and leaf path for delta

- keyswithmetadata.json
- package.json
- schemas/groups/electrical.json
- schemas/groups/notifications.json
- scripts/processSchemaFiles.js
This pull request tries to fix #273.
Keys documentation in master: [click here](https://www.niksula.hut.fi/~ristela1/signalk-documentation-master/keys/)
Keys documentation generated by this PR: [click here](https://www.niksula.hut.fi/~ristela1/signalk-documentation-with-object-documentation/keys/)
See for example `/vessels/<RegExp>/navigation/position`.
There are actually multiple parts to my changes but laziness & explorative coding led to just a single commit. The parts are:
1. replace `json-load-tree` with `json-schema-ref-parser` to
- load schema files locally
- let a library handle references instead of the previous `resolveReference`
2. fix `allOf` handling to properly handle more difficult cases
3. change Markdown generator to generate documentation for object types (+ fix a couple …
> Generate documentation for object types

- schemas/groups/resources.json
- Added a "bounds" key to store the chart's bounds (useful when it's not part of the chart format)
- Added a "wms" chart type
- Added a "chartLayers" key for WMS charts.
> Improvements to the chart model

- gitbook-docs/subscription_protocol.md
Explain the use case in plain english without abstract concepts.
Specify the precise path by separating the source reference inside
square brackets, because the reference is period delimited and
not entirely obvious which part of the path is hierarchy and which
property name.
Solves #271
> Multiple value subscriptions documentation

- index.js
- src/fullsignalk.js
- test/fullsignalk.js
$source references in the full tree were being filled with `no_source` values, because $source data was not being handled previously.
Fix and add a test to cover this case.
> fix: fix dollarsource references in full tree

- gitbook-docs/SUMMARY.md
- gitbook-docs/versioning.md
See #277.
The page specifies our versioning strategy. A combination of SchemaVer with a suffix to denote  interim or special releases
> Add page specifying versioning in Signal K

- keyswithmetadata.json
- schemas/definitions.json
Removed extra spaces from metadata description fields, and corrected m3 units to use superscript 3.
> Fixed typos and text formatting

- schemas/groups/electrical.json
- test/data/electrical.json
This is a cumulative (squash) of pull request #330 (which was canceled).  This replacement pull request has all the changes in one entry for simpler reading.
Major changes:
- Creation of common quality:  `chargerQualities` -- to be used by any device providing 'charging' to a battery
- Addition of `Solar` device type
- Addition of `Alternator` device type
There are also several cleanups in this submission, the largest is the scrubbing of the keyword `meta` which was applied incorrectly.  Other small changes include spelling, formatting for consistent punctuation, and the changing xxQuanities (A count) to xxQuality (a characteristic).
Pull request #330 had many changes and direction refinements; this new pull request is the end results. 
---
**UNRESOLVED ISSUE:**  One key issue unresolved …
> Add Alternator and Solar devices, create chargerQualitiies + cleanups 

- gitbook-docs/data_model_metadata.md
- schemas/definitions.json
- src/fullsignalk.js
- src/index.js
- test/fullsignalk.js
- test/schema-api.js
This PR adds functions `getMetadata(path)` and `getUnits(path)` to the published js module and uses these to include metadata in the main `/vessels`branch of the full model.
> feature: add metadata handling to js lib

- src/fullsignalk.js
Before this change the full tree had undefined meta properties for example
under notifications, where the path is dynamic and no metadata is
available in the schema for values' paths. Undefined properties
do not matter in creating JSON, as they are ignored, but matter in
validation, breaking schema validation in a way that is very hard
to detect.
> fix: don't create undefined meta properties

- gitbook-docs/data_model.md
I would like to remove sparse format from the specification.
I don't think it is a format on its own like full and delta are: it is just a partially populated full model. The less surface area the spec has the better.
I know that node server has no special support for sparse format, nor am I aware of any client code that relies on data being sparse.
> spec: remove sparse format

- package.json
Modify package.json so processSchemaFiles.js will run on windows. I have not tested, but I believe it previously would have run on other (non windows) platforms by running the js natively. This doesn't work on windows so I have modified it to run the js through node. Fully tested in Windows environment from clean install.
> fix npm install failing on windows platforms

- src/index.js
- test/messageValidation.js
The validSubscribeMessage and validUnsubscribeMessage were never being called when the tests ran, and so the message tests would always return valid even if there were errors. The actual 2 messages being tested (signalk-subscribe.json and signalk-unsubscribe.json) were in fact OK so no changes are needed to them.
> Fixed: bug in messages tests

- src/fullsignalk.js
- test/fullsignalk.js
Earlier fix to self being root relative was done only in
server and did not account for the case where you retrieve
the whole full document. Add tests for mmsi and uuid selfs.
> fix: make self relative to root in full

- .travis.yml
The recent outage on Travis CI lead me to look at the version of node we are using for Travis tests and the length of time they take to run. Currently we test using both v6 and v7 of node-js. The current version is 8.9.4 LTS or 9.4.0.
I have changed .travis.yml so that we only test using the latest v8 build of node-js which works fine.
> Update Travis tests to use latest node-js v8.x.x release

- gitbook-docs/versioning.md
Modified url in explanations to a fictional value
```
https://signalk.org/demospecification/...
```
rather than the real location of schemas
```
https://signalk.org/specification/
```
The purpose is to disassociate the explanation of version numbers from any actual releases and also to prevent any accidental overwriting of version numbers when docs are automatically updated by code. Also shows version numbers in the correct format.
> polish: improvements to documentation: versioning.md

- package-lock.json
- package.json
Added new dependency cross-var which allows npm environment variables to be included in scripts in a cross-platform way.
Substituted 'replace-in-file' in place of 'replace' package which is not cross platform compatible and is flagged as 'Unmaintained' by the author with no activity for over 3 years.
Tested on Windows 10 Version 1709 (build 16299.192) and Ubuntu xenial 16.04.3 LTS
> fix: modify package.json to make it cross platform compatible.

- schemas/groups/electrical.json
Fix issue #434.
Because the schema was previously invalid it is not clear whether or what previous data would have passed the TV4 schema validation, or not. Therefore the appropriate schema version bump as a result of this fix is unclear to me. One could take the view that this fixes a bug in the schema and does not change the schema itself, so should be an ADDITION??
I have added a new issue regarding the lack of schema validation tests #437.
> fix: invalid electrical schema

- CONTRIBUTING.md
First draft covering naming conventions for PRs and commits re issue #450.
Where should this be placed? I am thinking this becomes a section of Developer Notes which can be expanded to cover coding styles, etc in future, probably linked to the 'how can I help section'.
> WIP: docs: add notes covering naming conventions for pull requests

- gitbook-docs/data_model_metadata.md
Change documentation for `timeout` within metadata to remove reference to polling and bring in line with description and usage as described within the schema [definitions.json](https://github.com/SignalK/specification/blob/e87d62c7856ddb723048389cf8e335a564821cd2/schemas/definitions.json#L577).
closes #410
> docs: clarify timeout definition/usage

- gitbook-docs/data_model_metadata.md
- samples/full/0183-RMC-full.json
- samples/full/signalk-depth-meta-attr.json
- schemas/definitions.json
- test/data/full-valid/electrical-full_tree.json
- test/data/vessel-invalid/meta-missing-description.json
- test/data/vessel-invalid/meta-missing-units.json
- test/data/vessel-invalid/meta-with-invalid-enum.json
- test/data/vessel-valid/meta-with-enum.json
- test/data/vessel-valid/propulsion-sample.json
Schema modified to enforce the written specification that description and units must be present in meta.
Also added possibility for meta to include an enum list of possible values where the value is non numeric. This is not mandatory as at 1.0.x but the documentation notes that it is likely to become mandatory in future (see issue #439).
Samples and tests corrected to comply with the requirement.
Additional tests added to test the schema modifications.
Although the schema is not backwards compatible (making `description` mandatory where it wasn't previously), this change is just placing into the schema a requirement that was previously written in the specification. As such it can be viewed as an ADDITION (a schema change that is compatible with all historical data).
closes #439
> fix: modify schema to enforce `description` and `units`

- gitbook-docs/data_model_metadata.md
- schemas/definitions.json
- test/data/vessel-invalid/meta-with_displayScale_and_invalid_power.json
- test/data/vessel-valid/meta-with_displayScale_type.json
- test/data/vessel-valid/meta-with_displayScale_type_power.json
Add `type` within `displayScale` object to allow for non linear scales, ie. logarithmic, squareroot and power.
Tests added, sample extended and documentation updated.
closes #418
> feature: add type to meta/displayScale

- schemas/definitions.json
Ref issue #423.
This changes the schema in a non backwards compatible way, so will bump the version to 1.1.x. Do you want to create a separate branch for changes which will bump the schema version? I will have more to come next week as I'm intending to review the schema once I've completed the testing and document refactoring.
> fix: 'value' made a required property for anything using commonValueFields in schema

- schemas/discovery.json
The server software (not signalk schema) version was previously limited to the versioning regime mandated by signalk. This relaxes the schema to allow for servers which use alternative versioning systems.
> fix: accommodate any server software versioning scheme

- gitbook-docs/data_model_metadata.md
- samples/full/docs-data_model_metadata.json
Documentation discrepancy between the meta documentation and the sample file populating it. Also minor fix in the sample to ensure meta/description agrees with the value in the schema. This was introduced in PR #461 by me, sorry.
> fix: discrepancy between docs and sample json

- gitbook-docs/connection.md
- gitbook-docs/rest_api.md
- gitbook-docs/streaming_api.md
- samples/hello/docs-hello-minimal.json
- samples/hello/docs-hello.json
- schemas/hello.json
- src/index.js
- test/data/hello-invalid/version_bad.json
- test/data/hello-valid/master.json
- test/data/hello-valid/slave_minimal.json
- test/jsonSamplesAndTestFiles.js
Documentation improved.
Add new json schema file to be used to validate the hello message.
Add sample and test json files to illustrate and test usage.
resolves #473 
@tkurki be grateful if you could take a look at this. In particular there appears to be some commonality between the websocket hello message, the rest api, and the streaming api. None of which have to be implemented but I'm assuming if more than one is implemented the values (server name, signalK version, etc) should be the same in each place. I've assumed this and added to the documentation accordingly.
> docs: clarify websockets hello message

- package-lock.json
- package.json
- test/data/full-invalid/invalid-timestamp-ending-with-Z.json
- test/data/full-invalid/invalid-timestamp-subtle.json
Upgrade tv4-formats to latest version which works well with Webpack.
Previous versions used a try/catch import heuristic which does not play
well with webpack.
See ikr/tv4-formats@61450dc
(This PR replaces #498 - It also includes added tests so that my mistake in the first PR does not happen again).
> feature: update tv4-formats to latest version

- schemas/groups/tanks.json
The NMEA2000 standard makes a distinction between liveWell and baitWell.
We need to have that distinction too so we can accurately and
unequivocally translate some NMEA2000 PGNs.
See https://github.com/SignalK/n2k-signalk/pull/125 for a discussion of
the issue in the context of processing PGN130311 (temperature).
Example of NMEA2000 PGN with liveWell and baitWell:
https://github.com/sarfata/canboatjs/blob/9590c76ac8b7b265efeb143e318c8c87aaf437bf/lib/pgns.json#L16326
> feature: add baitWell as a type of tank

- package-lock.json
- package.json
Lodash is a fairly large dependency. Version 4 came out 3 years ago and
is what most packages use today. By upgrading to v4 we help people who
use signalk-specification: they will not need to bundle two versions of lodash.
> chore: update to lodash 4

- swagger/openapi.json
Goal: To have a well defined definition of the signalk REST API's in a standard format to ease development and testing of implementations. See https://www.openapis.org
Details: Created an initial openapi 3 definition that describes the Signalk API's, 
The definitions are very much a first cut, and there are many changes required as some of the interfaces are currently still WIP and therefore hard to define, but a commit was required to create the pull request :-)
This document was auto-generated from the Artemis server, using swagger 3 annotations to the Apache jersey implementation. See https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations.
When signalk-java (Artemis branch) is installed the swagger-ui can be viewed (and tried) against the Artemis server at …
> [WIP] Create openapi definitions for REST API's

- src/fullsignalk.js
This is a change only the code use by node server to build the full tree.
Currently when building a the full tree from deltas, this code will not include things like `hardwareVersion` and `productName` under `/sources` when included in deltas. This changes makes so all extra fields under `source` for deltas are included.
> feature: include all source information under `sources`

- gitbook-docs/SUMMARY.md
- gitbook-docs/connection.md
- gitbook-docs/streaming_api.md
This PR tries to include the bare minimum additions needed to specify a usable TCP streaming service. The more ambitious #294 stalled. Both Artemis and Node server already have streaming over TCP implemented, just need to check that they match this spec / alter the spec if needed.
> feature: specify streaming over TCP in more detail

- schemas/groups/sensors.json
- test/data/full-valid/ais.json
There was no designated home for AIS class previously in the
schema. For example OpenCPN distinguishes between
different AIS targets visually based on AIS class.
See also:
- https://github.com/SignalK/n2k-signalk/pull/163
- https://github.com/SignalK/signalk-parser-nmea0183/pull/160
> feature: add sensors.ais.class

- gitbook-docs/streaming_api.md
Cached values (for AIS targets particularly) cause mishap in OpenCpn. 
There is no way for the client to easily distinguish between the initial deltas from the cache and later, real updates, so it makes sense to make this behavior optional on the server, where the distinction between cached and real time updates is much clearer and distinct.
> feature: add sendCachedValues ws query parameter

- schemas/definitions.json
Extend the schema to cover the cases where meta contains
schema data for object valued properties like
"meta": {
"description": "The position of the vessel in 2 or 3 dimensions (WGS84 datum)",
"properties": {
"longitude": {
"type": "number",
"description": "Longitude",
"units": "deg",
"example": 4.98765245
},
"latitude": {
"type": "number",
"description": "Latitude",
"units": "deg",
"example": 52.0987654
},
"altitude": {
"type": "number",
"description": "Altitude",
"units": "m"
}
}
},
> fix: extend schema for meta properties

- src/fullsignalk.js
Previously if the delta was missing a path or value, the logged error message
was "Illegal value in delta: " along witht the pathValue. This is a bit misleading.
The new error message provides detail about whether the path and/or value is
missing along with source info.
Example of new message:
Delta is missing path in {"value":294.17}
from source {"label":"ydwg-2000","type":"NMEA2000","pgn":130312,"src":"41","instance":"0"}
> feature: add detail to delta error

- gitbook-docs/data_model.md
- gitbook-docs/subscription_protocol.md
- samples/delta/docs-data_model_meta_deltas.json
- schemas/delta.json
- src/fullsignalk.js
- test/data/delta-invalid/meta-missing-value.json
- test/data/delta-valid/meta-and-values.json
- test/data/delta-valid/meta-delta.json
There is currently no way to send `meta` data via deltas. This PR adds a new type of delta just for meta data.
The deltas would look like this:
```
{
updates: [
{
meta: [
{
"path": "electrical.batteries.1.voltage",
"value": {
"displayName": "Starter Battery V"
}
}
]
}
]
}
```
TODO
> feature: 'meta' deltas

- package.json
- scripts/processSchemaFiles.js
Update npm package to remove `core-js` warning about deprecated version.
Links to Signal K Server vulnerabilities and deprecated fix.
https://github.com/SignalK/signalk-server/pull/1508
Tested with updated npmjs version of signalk-schema@1.6.0 version with SignalK Server fixes.
As version 1.6.0 is not visible here and 1.7.0 seemed to cause some issues, This might need more investigation.
Which commit is npmjs 1.6.0?
> fix: deprecated package updated

- package.json
- test/schemaReferences.js
- `docs:keys` need to be run before `js:dist` to get `keyswithmetadata.json` to `src` folder and then copied to `dist` folder
- test updated to use `@apidevtools/json-schema-ref-parser`
> chore: prepublish run order change, json-schema-ref-parser update

- src/index.js
Remove the duplicate require & exports line and change the remaining import to include .json in the file reference. This makes the require Webpack-friendly and allows usage in browser environment.
> fix: keyswithmetadata require
